server:
  host: 0.0.0.0
  port: 5001
filters:
  subjects:
  - 电子账单
  - 对账单
  - 信用卡账单
  exclude_subjects:
  - 礼品
  - 优惠
  - 活动
  - Promotion
  - Deals
reminder:
  days_before:
  - 1
  - 0
report:
  months_to_keep: 12
